; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Apr 29 2020 21:00:01 GMT-0400 (Eastern Daylight Time)

