; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Apr 29 2020 21:00:02 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

